# Copyright (C) 2026 Sugar Labs
#
# SPDX-License-Identifier: GPL-3.0-or-later

import json

from generation.rag import get_api_reference
from generation.rag import get_ui_design_reference


def build_system_prompt(spec, references=()):
    categories = spec.learning_categories()
    learning_direction = '\n\n'.join(
        _CATEGORY_BLOCKS.get(category, _CATEGORY_BLOCKS['creation'])
        for category in categories
    ) or _CATEGORY_BLOCKS['creation']
    if spec.template != 'auto':
        learning_direction = '%s\n%s' % (
            learning_direction,
            _TEMPLATE_HINTS.get(spec.template, ''),
        )
    reference_text = _format_references(references)
    return (
        'You are Sugar Activity on Demand, a planner for safe, '
        'learner-friendly Sugar activities that will be generated by an '
        'LLM code generator.\n\n'
        'PRIORITY RULES\n'
        '1. Return one JSON object and no Markdown.\n'
        '2. Plan for Sugar Activity and GTK3, not Gtk.Application.\n'
        '3. Design the actual activity the learner asked for. Do not force '
        'the idea into a canned quiz/canvas/grid unless that is truly the '
        'best design.\n'
        '4. Retrieved references are API and pattern examples, not templates '
        'to copy. Use them to understand how Sugar activities are structured, '
        'how the toolbar/canvas lifecycle works, and how Journal persistence '
        'is wired.\n'
        '5. The provider code generator owns the activity.py source for '
        'provider jobs. Do not plan a local-template substitute.\n'
        '6. Do not request network access, subprocesses, or unrestricted '
        'filesystem access.\n'
        '7. The RAG step has already supplied the relevant Sugar examples. '
        'Do not ask for more ingestion, training, uploads, or setup.\n'
        '8. If the learner request contains a current activity.py excerpt, '
        'treat it as an iterative refinement: preserve the working activity '
        'and change only what the refinement asks for.\n'
        '9. Selected learning-area cards are discovery/RAG hints, not feature '
        'requirements. Never inject math problems, quizzes, vocabulary, '
        'assessment, reflection, explanations, classroom roles, or other '
        'curriculum unless the learner request, confirmed answers, or '
        'reference image explicitly asks for it. Respect the age band and '
        'license without changing the requested activity.\n'
        '10. Plan the complete interface using the Sugar whole-interface '
        'contract below. Do not plan a generic card grid, web dashboard, or '
        'permanent sidebar by default.\n'
        '11. A reference-image brief describes activity content and settled '
        'visual decisions, not a license to copy browser/editor chrome. '
        'Use this strict priority: explicit learner request first; visible '
        'reference decisions inside the target activity second; Sugar-native '
        'adaptation only for host chrome and details not settled by the image; '
        'generic layout preferences last. Preserve every visible functional '
        'region and control one-for-one, including approximate proportions, '
        'alignment, ordering, color relationships, state, and relative '
        'left/center/right placement. Do not omit, merge, move, or redesign a '
        'target region just to make it look more Sugar-native. Relocate or '
        'omit only browser, editor, Studio, export, and other host controls '
        'listed as Ignore regions.\n\n'
        '%s\n\n%s\n\n'
        'OPTIONAL DISCOVERY DIRECTION (DO NOT FORCE INTO FEATURES)\n%s\n\n'
        'RETRIEVED SUGAR REFERENCES\n%s\n\n'
        'Return these JSON fields:\n'
        '- name: short activity name\n'
        '- template: closest implementation/reference family: canvas, '
        'carrom, chess, grid, narrative, quiz, or utility. This is metadata '
        'only and must never replace or alter the requested mechanics.\n'
        '- activity_kind: the specific kind of activity to build, in your '
        'own words\n'
        '- summary: one sentence\n'
        '- learner_goal: the concrete activity/play/use goal; educational '
        'only when explicitly requested\n'
        '- learner_steps: 3 to 5 short steps for using or playing it\n'
        '- interaction_model: how learners interact with the activity\n'
        '- ui_regions: 3 to 6 Sugar regions, identifying the dominant learner '
        'workspace and any truly persistent panel\n'
        '- toolbar_actions: primary actions that belong in the main toolbar\n'
        '- palette_actions: secondary or contextual actions that belong in '
        'Sugar palettes or sub-toolbars\n'
        '- feedback_model: visible selection, progress, success, error, and '
        'empty-state feedback\n'
        '- color_model: grayscale activity chrome, meaningful content color, '
        'and any learner/XO color ownership\n'
        '- responsive_behavior: how the workspace dominates at 1024x768 and '
        '1200x900 without clipping\n'
        '- state_schema: short description of the data saved to the Journal\n'
        '- word_bank: up to 8 useful words\n'
        '- features: 3 to 6 concrete, request-specific mechanics visible in '
        'the finished activity. Never copy generic features from the closest '
        'template family.\n'
        '- classroom_flow: optional only when classroom use was requested\n'
        '- teacher_notes: optional only when teacher facilitation was requested\n'
        '- assessment_prompts: optional only when assessment was requested\n'
        '- materials: optional only when physical materials were requested\n'
        '- refinement_notes: optional list of changes to preserve or apply '
        'when this is a refinement\n'
        '- chess_show_move_log: optional boolean for chess activities; false '
        'means use a clean board without a move-history panel\n'
        '- questions: optional list of question/answer objects for quizzes\n'
        '- starter_text: optional opening text for narrative activities\n'
    ) % (
        get_api_reference(),
        get_ui_design_reference(),
        learning_direction,
        reference_text or 'No external examples were retrieved.',
    )


def build_user_prompt(spec):
    return (
        'Plan a bespoke Sugar activity from this structured learner request. '
        'Use the retrieved Sugar references as context for how real Sugar '
        'activities are built, then make the plan specific enough that a '
        'second model call can generate a complete activity.py. Do not fall '
        'back to canned templates, placeholders, or generic demos:\n\n%s'
        % spec.to_prompt()
    )


def extract_json_object(text):
    if not isinstance(text, str):
        raise ValueError('Provider response must be text.')

    candidate = text.strip()
    if candidate.startswith('```'):
        first_newline = candidate.find('\n')
        last_fence = candidate.rfind('```')
        if first_newline >= 0 and last_fence > first_newline:
            candidate = candidate[first_newline + 1:last_fence].strip()

    try:
        value = json.loads(candidate)
    except json.JSONDecodeError:
        start = candidate.find('{')
        end = candidate.rfind('}')
        if start < 0 or end <= start:
            raise ValueError('Provider response did not contain JSON.')
        try:
            value = json.loads(candidate[start:end + 1])
        except json.JSONDecodeError as error:
            raise ValueError('Provider returned invalid JSON: %s' % error)

    if not isinstance(value, dict):
        raise ValueError('Provider JSON must be an object.')
    return value


def _format_references(references):
    blocks = []
    for index, document in enumerate(references[:5], 1):
        text = ' '.join(document.text.split())
        blocks.append(
            'Reference %d - %s:\n%s' % (index, document.title, text[:1800])
        )
    return '\n\n'.join(blocks)


_CATEGORY_BLOCKS = {
    'logic_math': (
        'Use this only to retrieve useful examples. Add patterns, reasoning, '
        'or answers only when the activity request itself calls for them.'
    ),
    'science': (
        'Use this only to retrieve useful examples. Add experiments, '
        'measurements, or science content only when explicitly requested.'
    ),
    'language': (
        'Use this only to retrieve useful examples. Add vocabulary, reading, '
        'or writing mechanics only when explicitly requested.'
    ),
    'tools_utils': (
        'Use this only to retrieve useful examples. Build the exact utility '
        'described by the activity request.'
    ),
    'games': (
        'Favor a clear play loop, visible goals, understandable state, and '
        'feedback that supports experimentation instead of punishment.'
    ),
    'creation': (
        'When the request is creative, favor direct creation controls and a '
        'learner-owned artifact that can be revised and saved.'
    ),
}

_TEMPLATE_HINTS = {
    'canvas': (
        'If a canvas is appropriate, use direct manipulation and a clear/reset '
        'action.'
    ),
    'carrom': (
        'If carrom is appropriate, use a square board, corner pockets, coins, '
        'a striker/aim marker, two-player turns, scoring, fouls, and Journal '
        'persistence.'
    ),
    'chess': (
        'If chess is appropriate, use an 8x8 board, turns, pieces, move '
        'feedback, and Journal persistence.'
    ),
    'grid': (
        'If a grid is appropriate, use visible state, patterns, and '
        'reversible choices.'
    ),
    'narrative': (
        'If writing is appropriate, use a large editable area and a useful '
        'starter.'
    ),
    'quiz': (
        'If a quiz is appropriate, use learner-friendly questions and '
        'feedback.'
    ),
    'utility': (
        'If a utility is appropriate, use visible input and immediate output.'
    ),
}
